# Site settings
title: Iran University of Science and Technology
course_name: Artificial Intelligence
course_description: This course introduces students to the basic knowledge representation, problem solving, and learning methods of artificial intelligence. you will learn the foundational principles that drive AI applications and practice implementing some of these systems. We will be following the excellent <a href=http://ai.berkeley.edu>UC-Berkeley CS188</a> course material developed by Dan Klein and Pieter Abbeel.
course_semester: "Fall 2020 "
description: |
    Instructor: Mohammad Taher Pilevar and Sauleh Eetemadi

message: #Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/ai99" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/ai99" # the base hostname & protocol for your site
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: tpilehvar 
github_username:  pilehvar
authorurl: "webpages.iust.ac.ir/pilehvar/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
